### ISSUE TITLE
Settings of third skycon is applied to the first two skycons

### ISSUE THREAD

**Issue by melvingrootenboers** [Mcpoowl/mx-skycons#2]
Steps to reproduce:
1. Add three Skycons on a page (all with the same icon)
2. Configure the first like the image below:
![image](https://cloud.githubusercontent.com/assets/10810429/13812384/1d23819e-eb7c-11e5-8cab-a78841796242.png)
3. Configure the second like the image below:
![image](https://cloud.githubusercontent.com/assets/10810429/13812401/3a7ad67a-eb7c-11e5-9970-e4168360a744.png)
4. Configure the third like the image below:
![image](https://cloud.githubusercontent.com/assets/10810429/13812408/46c8dd82-eb7c-11e5-8358-4af478ad5572.png)
5. Run the project and open the page

Result:
All skycons are animated and single colored
![image](https://cloud.githubusercontent.com/assets/10810429/13812430/61d9cc94-eb7c-11e5-9a08-35320ea677fb.png)

Expected result:
The first skycon is animated and colored
The second skycon is unanimated and single colored
The third skycon is animated and single colored
![image](https://cloud.githubusercontent.com/assets/10810429/13812495/d6793832-eb7c-11e5-829b-388eae2ce167.png)

**Comment by Mcpoowl** [comment]
Hi Melvin,

Thanks for the issue. I was able to reproduce it. Did you perhaps find a fix for it, or did you just notice the error? 

Thanks again. I'll see what I can do!
